name: Monitor Website

on:
  schedule:
    - cron: '*/5 * * * *'  # Uruchamiaj co 5 minut

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run website status check
        run: node checkWebsiteStatus.js
